service: twenty-one-cen-backend
frameworkVersion: '3'

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
  serverless-offline:
    useChildProcesses: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-1'}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    DEBUG: '*'
    NODE_ENV: ${self:provider.stage}
    MONGO_URL: ${file(env.yml):MONGO_URL}

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
